apiVersion: v1
kind: Service
metadata:
  name: php-service
  labels:
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: php
    tier: backend
  ports:
    - port: 9000
      targetPort: 9000