apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-deployment
  labels:
    tier: backend
spec:
  selector:
    matchLabels:
      app: php
      tier: backend
  template:
    metadata:
      labels:
        app: php
        tier: backend
    spec:
      containers:
        - name: php
          image: php-fpm
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
         # volumeMounts:
          #  - name: pv
          #    mountPath: /app